name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # メインブランチ名に合わせて変更

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Clone source repository
        run: git clone https://$TOKEN@github.com/K-Sy/EtymoProto.git
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Install dependencies
        run: npm install
        working-directory: ./EtymoProto

      - name: Build
        run: npm run build
        working-directory: ./EtymoProto

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_PAT }}
          publish_dir: ./EtymoProto/dist
          publish_branch: gh-pages
          destination_repo: yourusername/yourusername.github.io
